HeadNode:
  CustomActions:
    OnNodeConfigured:
      Sequence:
        - Script: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/storage/mountpoint_s3/assets/install.sh
        - Script: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/storage/mountpoint_s3/assets/mount.sh
          Args:
            - <<DEMO-BUCKET-NAME>>
            - <<HOST-FILESYSTEM-PATH>>
            - '--allow-delete --allow-root'
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    S3Access:
      - BucketName: <<DEMO-BUCKET-NAME>>
        EnableWriteAccess: true
  InstanceType: c5.xlarge
  Networking:
    SecurityGroups:
      - <<Your Security Group>>
    SubnetId: <<Your Subnet ID>>
  Ssh:
    KeyName: <<Your ed25519 key>>
Image:
  Os: alinux2
Monitoring:
  Dashboards:
    CloudWatch:
      Enabled: true
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      DeletionPolicy: Delete
      Enabled: true
      RetentionInDays: 5
Region: us-east-1
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - CapacityType: ONDEMAND
      ComputeResources:
        - DisableSimultaneousMultithreading: true
          Efa:
            Enabled: false
          Instances:
            - InstanceType: c7i.8xlarge
          MaxCount: 1
          MinCount: 1
          Name: pclustercr1
      CustomActions:
        OnNodeConfigured:
          Sequence:
            - Script: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/storage/mountpoint_s3/assets/install.sh
            - Script: https://aws-hpc-recipes.s3.us-east-1.amazonaws.com/main/recipes/storage/mountpoint_s3/assets/mount.sh
              Args:
                - <<DEMO-BUCKET-NAME>>
                - <<HOST-FILESYSTEM-PATH>>
                - '--allow-delete --allow-root'
            - Script: https://aws-hpc-blog.s3.amazonaws.com/s3mountpoint/s3-mp-install-ior.sh
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        S3Access:
          - BucketName: <<DEMO-BUCKET-NAME>>
            EnableWriteAccess: true
      Name: queue1
      Networking:
        PlacementGroup:
          Enabled: false
        SecurityGroups:
          - <<Your Security Group>>
        SubnetIds:
          - <<Your Subnet ID>>
